# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IPL' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IPL






  pod 'RNImageCropPicker', :path => '../node_modules/react-native-image-crop-picker'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  pod 'RealmJS', :path => '../node_modules/realm'

  pod 'react-native-image-resizer', :path => '../node_modules/react-native-image-resizer'

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'

  pod 'RNShare', :path => '../node_modules/react-native-share'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'

  pod 'RNFBApp', :path => '../node_modules/@react-native-firebase/app'

  pod 'RNFBAuth', :path => '../node_modules/@react-native-firebase/auth'

  pod 'RNFBFirestore', :path => '../node_modules/@react-native-firebase/firestore'

  target 'IPLTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'IPL-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IPL-tvOS

  target 'IPL-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
